"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UNKNOWN_ERROR = exports.UNKNOWN = exports.UNEXPECTED_AUTH_PROCESS = exports.UNDETERMINED = exports.UCCESS_MSG_RETRIEVE_ALL_LOCATION = exports.SUCCESS_MSG_RETRIEVE_LOCATION = exports.SUCCESS_MSG_RETRIEVE_CONTENT_DELIVERY = exports.SUCCESS_MSG_RETRIEVE_ALL_LOCATION = exports.SUCCESS_MSG_RECEIVE_FCM_TOKEN = exports.SUCCESS_MSG_INIT = exports.SUCCESS_MSG_DELETE_LOCATION_TABLE_ITEM = exports.SUCCESS_MSG_DELETE_LOCATION_TABLE = exports.SUCCESS_MSG_CHECK_PERMISSION = exports.SUCCESS_MSG_APP_KEY = exports.SUCCEEDED = exports.REACH_TRACK_SUCCESS = exports.REACH_TRACK_ERROR = exports.NO_INTERNET_CONNECTION = exports.M_ID = exports.MISSING_KEY_ERR = exports.LOCATION_PERMISSION_NOT_GRANTED = exports.LOCATION_DATA_WAS_NOT_INSERTED = exports.LOCATION_DATA_UPDATE_SUCCESSFULLY = exports.LOCATION_DATA_UPDATE_FAILED = exports.LOCATION_DATA_SAVE_TO_DB = exports.LOADING = exports.IS_CLIENT = exports.IS_AD_ACTIVE = exports.INVALID_FCM_TOKEN_ERR = exports.IMPRESSION_TRACK_SUCCESS = exports.IMPRESSION_TRACK_ERROR = exports.IDLE = exports.GRANTED = exports.FOOT_PRINTS_LOCAL_DB = exports.FCM_TOKEN = exports.FAILED = exports.ERR_NO_LOCATION_FOUND = exports.ERR_NO_CONTENT_DELIVERY_FOUND = exports.ERR_MSG_RETRIEVE_LOCATION = exports.ERR_MSG_INIT = exports.ERR_MSG_GET_LOCATION = exports.ERR_MSG_DELETE_LOCATION_TABLE = exports.ERR_MSG_CONTENT_DELIVERY = exports.ERR_MSG_CHECK_PERMISSION = exports.DENIED = exports.DATABASE_NOT_INITIALIZED = exports.CONTENT_DELIVERY_WAS_NOT_INSERTED = exports.CONTENT_DELIVERY_DATA_SUCCESS = exports.CONTENT_DELIVERY_DATA_SAVE_TO_DB = exports.CONTENT_DELIVERY_DATA_FAILED = exports.CAMPAIGN_ID = exports.BASE_URL = exports.APP_KEY_VALIDATION_FAILED = exports.APP_KEY = exports.AN_UNEXPECTED_ERR_OCCUR = exports.AN_ERR_OCCUR = exports.AD_ID_SUCCESS = exports.AD_ID_ERROR = exports.AD_ID = exports.ADS_LAYOUT = void 0;
const IS_CLIENT = exports.IS_CLIENT = 'isClient';
const APP_KEY = exports.APP_KEY = 'APP_KEY';
const M_ID = exports.M_ID = 'M_ID';
const ADS_LAYOUT = exports.ADS_LAYOUT = 'ADS_LAYOUT';
const CAMPAIGN_ID = exports.CAMPAIGN_ID = 'CAMPAIGN_ID';
const IS_AD_ACTIVE = exports.IS_AD_ACTIVE = 'IS_AD_ACTIVE';
const AD_ID = exports.AD_ID = 'AD_ID';
const BASE_URL = exports.BASE_URL = 'BASE_URL';
const FCM_TOKEN = exports.FCM_TOKEN = 'FCM_TOKEN';
const FOOT_PRINTS_LOCAL_DB = exports.FOOT_PRINTS_LOCAL_DB = 'foot_prints_local_db.db';
const SUCCESS_MSG_APP_KEY = exports.SUCCESS_MSG_APP_KEY = 'App key has been set and validated successfully.';
const ERR_MSG_INIT = exports.ERR_MSG_INIT = 'App key validation failed. Please check your app key.';
const SUCCESS_MSG_INIT = exports.SUCCESS_MSG_INIT = 'Database initialized successfully.';
const ERR_MSG_CHECK_PERMISSION = exports.ERR_MSG_CHECK_PERMISSION = 'App key validation failed. Unable to check location permissions.';
const SUCCESS_MSG_CHECK_PERMISSION = exports.SUCCESS_MSG_CHECK_PERMISSION = 'App location permission successfully.';
const ERR_MSG_GET_LOCATION = exports.ERR_MSG_GET_LOCATION = 'App key validation failed. Unable to retrieve location.';
const ERR_MSG_RETRIEVE_LOCATION = exports.ERR_MSG_RETRIEVE_LOCATION = 'App key validation failed. Unable to retrieve location from the database.';
const ERR_NO_LOCATION_FOUND = exports.ERR_NO_LOCATION_FOUND = 'No location data found in the database.';
const ERR_NO_CONTENT_DELIVERY_FOUND = exports.ERR_NO_CONTENT_DELIVERY_FOUND = 'No content delivery data found in the database.';
const UCCESS_MSG_RETRIEVE_ALL_LOCATION = exports.UCCESS_MSG_RETRIEVE_ALL_LOCATION = 'Location data retrieved successfully from the database.';
const SUCCESS_MSG_RETRIEVE_LOCATION = exports.SUCCESS_MSG_RETRIEVE_LOCATION = 'Location data retrieved successfully from the database.';
const SUCCESS_MSG_RETRIEVE_ALL_LOCATION = exports.SUCCESS_MSG_RETRIEVE_ALL_LOCATION = 'All location data retrieved successfully from the database.';
const SUCCESS_MSG_RETRIEVE_CONTENT_DELIVERY = exports.SUCCESS_MSG_RETRIEVE_CONTENT_DELIVERY = 'Content delivery data retrieved successfully from the database.';
const ERR_MSG_DELETE_LOCATION_TABLE = exports.ERR_MSG_DELETE_LOCATION_TABLE = 'App key validation failed. Unable to delete the database table.';
const ERR_MSG_CONTENT_DELIVERY = exports.ERR_MSG_CONTENT_DELIVERY = 'App key validation failed. Unable to get content delivery data.';
const SUCCESS_MSG_DELETE_LOCATION_TABLE = exports.SUCCESS_MSG_DELETE_LOCATION_TABLE = 'Table deleted successfully.';
const SUCCESS_MSG_DELETE_LOCATION_TABLE_ITEM = exports.SUCCESS_MSG_DELETE_LOCATION_TABLE_ITEM = 'Delete location successfully.';
const SUCCESS_MSG_RECEIVE_FCM_TOKEN = exports.SUCCESS_MSG_RECEIVE_FCM_TOKEN = 'FCM token sent successfully.';
const GRANTED = exports.GRANTED = 'granted';
const DENIED = exports.DENIED = 'denied';
const UNDETERMINED = exports.UNDETERMINED = 'undetermined';
const UNKNOWN = exports.UNKNOWN = 'unknown';
const LOCATION_PERMISSION_NOT_GRANTED = exports.LOCATION_PERMISSION_NOT_GRANTED = 'Location permission is not granted. Please enable location services.';
const APP_KEY_VALIDATION_FAILED = exports.APP_KEY_VALIDATION_FAILED = 'App key validation failed.';
const UNEXPECTED_AUTH_PROCESS = exports.UNEXPECTED_AUTH_PROCESS = 'Unexpected status returned from authentication process.';
const SUCCEEDED = exports.SUCCEEDED = 'succeeded';
const FAILED = exports.FAILED = 'failed';
const LOADING = exports.LOADING = 'loading';
const IDLE = exports.IDLE = 'idle';
const AN_ERR_OCCUR = exports.AN_ERR_OCCUR = 'An error occurred';
const DATABASE_NOT_INITIALIZED = exports.DATABASE_NOT_INITIALIZED = 'Database is not initialized.';
const LOCATION_DATA_WAS_NOT_INSERTED = exports.LOCATION_DATA_WAS_NOT_INSERTED = 'Location data was not inserted into the database.';
const CONTENT_DELIVERY_WAS_NOT_INSERTED = exports.CONTENT_DELIVERY_WAS_NOT_INSERTED = 'Content delivery data was not inserted into the database.';
const LOCATION_DATA_SAVE_TO_DB = exports.LOCATION_DATA_SAVE_TO_DB = 'Location data saved to database.';
const CONTENT_DELIVERY_DATA_SAVE_TO_DB = exports.CONTENT_DELIVERY_DATA_SAVE_TO_DB = 'Content delivery data saved to database.';
const MISSING_KEY_ERR = exports.MISSING_KEY_ERR = 'is missing. Please provide a valid';
const INVALID_FCM_TOKEN_ERR = exports.INVALID_FCM_TOKEN_ERR = 'Invalid FCM token. Please provide a valid';
const NO_INTERNET_CONNECTION = exports.NO_INTERNET_CONNECTION = 'No internet connection';
const LOCATION_DATA_UPDATE_SUCCESSFULLY = exports.LOCATION_DATA_UPDATE_SUCCESSFULLY = 'Location data updated successfully';
const LOCATION_DATA_UPDATE_FAILED = exports.LOCATION_DATA_UPDATE_FAILED = 'Location data update failed';
const UNKNOWN_ERROR = exports.UNKNOWN_ERROR = 'Unknown error';
const AN_UNEXPECTED_ERR_OCCUR = exports.AN_UNEXPECTED_ERR_OCCUR = 'An unexpected error occurred';
const CONTENT_DELIVERY_DATA_SUCCESS = exports.CONTENT_DELIVERY_DATA_SUCCESS = 'Get content delivery details successfully.';
const CONTENT_DELIVERY_DATA_FAILED = exports.CONTENT_DELIVERY_DATA_FAILED = 'Get content delivery details failed.';
const AD_ID_SUCCESS = exports.AD_ID_SUCCESS = 'Get advertising id successfully.';
const AD_ID_ERROR = exports.AD_ID_ERROR = 'Get Advertising ID failed. Please try again later.';
const REACH_TRACK_SUCCESS = exports.REACH_TRACK_SUCCESS = 'Reach tracking update successfully';
const REACH_TRACK_ERROR = exports.REACH_TRACK_ERROR = 'Reach tracking update failed';
const IMPRESSION_TRACK_SUCCESS = exports.IMPRESSION_TRACK_SUCCESS = 'Impression tracking update successfully';
const IMPRESSION_TRACK_ERROR = exports.IMPRESSION_TRACK_ERROR = 'Impression tracking update failed';
//# sourceMappingURL=Constants.js.map